<?php

namespace Tests\Feature;

use App\Client;
use Tests\CreatesClientInvoiceResources;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AllyPercentageTest extends TestCase
{
    use RefreshDatabase;
    use CreatesClientInvoiceResources;

    /**
     *
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = factory(Client::class)->create();

    }

    /**
     * @test
     */
    public function a_private_pay_client_with_provider_pay_is_3()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->client->business);

        $this->assertEquals(config('ally.bank_account_fee'), $this->client->getAllyPercentage());
    }


    /**
     * @test
     */
    public function a_private_pay_client_with_credit_card_is_5()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->createCreditCard('visa'));

        $this->assertEquals(config('ally.credit_card_fee'), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_private_pay_client_with_amex_is_6()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->createCreditCard('amex'));

        $this->assertEquals(config('ally.amex_card_fee'), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_balance_payer_with_provider_pay_is_3()
    {
        $clientPayer = $this->createBalancePayer();
        $clientPayer->payer->setProviderPay();

        $this->assertEquals(config('ally.bank_account_fee'), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_split_payer_uses_the_higher_split_percentage()
    {
        $clientPayer1 = $this->createPrivateSplitPayer(0.49);
        $clientPayer2 = $this->createSplitPayer(0.51);
        $clientPayer2->payer->setProviderPay();

        $this->assertEquals(config('ally.bank_account_fee'), $this->client->getAllyPercentage());
    }
}
