<?php

namespace Tests\Feature;

use App\Billing\BillingCalculator;
use App\Billing\FeeOverrideRule;
use App\Billing\Payments\Methods\CreditCard;
use App\Billing\Payments\PaymentMethodType;
use App\Client;
use Tests\CreatesClientInvoiceResources;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AllyPercentageTest extends TestCase
{
    use RefreshDatabase;
    use CreatesClientInvoiceResources;

    /** @var \App\Client */
    private $client;

    /**
     *
     */
    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = factory(Client::class)->create();

    }

    /**
     * @test
     */
    public function a_private_pay_client_with_provider_pay_is_3()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->client->business);

        $this->assertEquals(BillingCalculator::getBankAccountRate(), $this->client->getAllyPercentage());
    }


    /**
     * @test
     */
    public function a_private_pay_client_with_credit_card_is_5()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->createCreditCard('visa'));

        $this->assertEquals(BillingCalculator::getCreditCardRate(), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_private_pay_client_with_amex_is_6()
    {
        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod($this->createCreditCard('amex'));

        $this->assertEquals(BillingCalculator::getAmexRate(), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_balance_payer_with_provider_pay_is_3()
    {
        $clientPayer = $this->createBalancePayer();
        $clientPayer->payer->setProviderPay();

        $this->assertEquals(BillingCalculator::getBankAccountRate(), $this->client->getAllyPercentage());
    }

    /**
     * @test
     */
    public function a_split_payer_uses_the_higher_priority()
    {
        $clientPayer1 = $this->createPrivateSplitPayer(0.50);
        $clientPayer1->update(['priority' => 2]);
        $clientPayer2 = $this->createSplitPayer(0.50);
        $clientPayer2->payer->setProviderPay();

        $this->assertEquals(BillingCalculator::getBankAccountRate(), $this->client->getAllyPercentage());
    }

    /** @test */
    function getting_the_ally_percent_directly_from_the_client_should_respect_overrides()
    {
        $override = FeeOverrideRule::create([
            'business_id' => $this->client->business_id,
            'rate' => 0.02,
            'payment_method_type' => PaymentMethodType::CC(),
        ]);

        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod(factory(CreditCard::class)->create());
        $this->assertEquals(PaymentMethodType::CC(), $this->client->getPaymentType());
        $this->assertEquals($override->getRate(), $this->client->getAllyPercentage());
    }

    /** @test */
    function getting_the_ally_percent_directly_from_the_client_should_respect_override_types()
    {
        $override = FeeOverrideRule::create([
            'business_id' => $this->client->business_id,
            'rate' => 0.08,
            'payment_method_type' => PaymentMethodType::AMEX(),
        ]);

        $this->createPrivateBalancePayer();
        $this->client->setPaymentMethod(factory(CreditCard::class)->states('amex')->create());
        $this->assertEquals(PaymentMethodType::AMEX(), $this->client->getPaymentType());
        $this->assertEquals($override->getRate(), $this->client->getAllyPercentage());
    }
}
